name: Deploy GHPages

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
        - name: Init
          run: mkdir public
    
        - name: Touch html file
          run: |
               echo "hello from github actions. <b> the current date is" > public/index.html \
               && date >> public/index.html \ 
               && echo ".</b>" >> public/index.html
        
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public
