name: Deploy GHPages

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
        - name: Init
          run: mkdir public
          
        - name: Debuggging with tmate
          # You may pin to the exact commit or the version.
          # uses: GitHub30/action-tmate@7a4c478c598693c8e03332a5d349360704f758e0
          uses: GitHub30/action-tmate@master2
    
        - name: Touch html file
          run: |
               echo "hello from github actions. <b> the current date is" > public/index.html 
               && date >> public/index.html 
               && echo ".</b>" >> public/index.html
        
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public
